name: cd
on:
  push:
    # branches: [cd-test-master]
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: cimg/go:1.15
    steps:
      - run: echo $GITHUB_REF
      - name: Setup required permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # ensures we fetch all history for all branches and tags
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Verify Build # maybe we should move this to a release triggered worfklow
      #   run: ./verify_examples.sh
